name: number_trivia_clean_architecture
description: TDD Clean Architecture with BLoC

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.1 <3.0.0"

dependencies:
  dartz: ^0.10.1
  data_connection_checker: ^0.3.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  http: ^0.13.4
  shared_preferences: ^2.0.11
 
dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17

flutter:
  uses-material-design: true
